env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  'comma-dangle': ['error', { 'arrays': 'always-multiline', 'objects': 'always-multiline', 'imports': 'never', 'exports': 'never', 'functions': 'never' }]
  global-require: 0
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - 'webpack.config.js'
ignorePatterns:
  - 'dist'
